# Style/NumericLiterals:
#   Exclude:
#     - 'db/schema.rb'
# Layout/EmptyLinesAroundBlockBody:
#   Exclude:
#     - 'db/schema.rb'
# Style/StringLiterals:
#   Exclude:
#     - 'db/schema.rb'
# Style/WordArray:
#   Exclude:
#     - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 95
  IgnoredPatterns: ['\A\s*\#']
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Include:
    - 'app/services/**/*'
    - 'app/parsers/**/*'
